spring.application.name=HotelBooking

server.port=${PORT:8080}

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://ep-late-resonance-apznthug-pooler.c-7.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_03giNoWFPxzM
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# ===============================
# JWT CONFIGURATION
# ===============================
secreteJwtString=mySecretKey123456789abcdefghijklmnopqrstuvwxyz

# ===============================
# MAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hotelgrand0709@gmail.com
spring.mail.password=fxzg cdsb gdes qzhl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===============================
# FILE UPLOAD CONFIGURATION
# ===============================
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB

# ===============================
# STRIPE CONFIGURATION
# ===============================
stripe.api.public.key=
stripe.api.secret.key=

cloudinary.cloud-name=ddyvc4ozg
cloudinary.api-key=538794492912352
cloudinary.api-secret=VjKZwYkKfkhtxvDY1-yEPBKYgcI